keys:
  - &user_agondek_blackwood age1xcdc26y6nqhqrtgqj9lkx2ew58pjsgehxt3g44gtzy2q8g93upaq22ryjm
  - &server_blackwood age1fszuf08p7xmm47t37dtuyj0s0gfydmnk5sdkx3jvg2vm4ph89shs3ekjul
  - &server_nixos_flake_test age15vmnelwhcz777qnatt0ku6v62wj3jassrydqh68ywpe8rl8gysds76gs0s
  - &server_pasithea age00000000000000000000000000000000000000000000000000000000000
  - &server_plutus age1r9kndf5u3ng0wfj08cqkhyr0zs0a4yyhdvfc0r6cq35gjywgyemq2quhc8
  - &server_vm-utility-drone age00000000000000000000000000000000000000000000000000000000000
creation_rules:
  - path_regex: blackwood/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *user_agondek_blackwood
        - *server_blackwood
  - path_regex: nixos-flake-test/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *server_nixos_flake_test
  - path_regex: pasithea/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *server_pasithea
  - path_regex: plutus/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *server_plutus
  - path_regex: vm-utility-drone/secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *user_agondek_blackwood
        - *server_vm-utility-drone
