# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "ata_piix" "mptspi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/1db72b99-df4c-4e7b-be7e-6d17912c9923";
      fsType = "btrfs";
    };
  fileSystems."/var/lib/docker" =
    { device = "/dev/disk/by-uuid/50479407-99f8-4655-929c-12229c458bfd";
      fsType = "ext4";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/b1a3985e-74c2-422e-bfc5-950f3d63119f"; }
    ];

  nix.maxJobs = lib.mkDefault 4;
}
