name: "nixos-flake-test"
on:
  pull_request:
  push:
jobs:
  tests:
    name: nixos-flake-test build configuration check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
       # Flakes do not like shallow clones
      with:
        fetch-depth: 0

    # TODO: agondek
    # This is just embarassing, please improve
    - name: ""
      run: >
        sed -i 's/default = true;/default = false;/g' cfg/fonts/default.nix && git add -A

    - uses: cachix/install-nix-action@v31
      with:
        nix_path: "nixpkgs=https://releases.nixos.org/nixos/25.05/nixos-25.05.809913.7ff837017c3b/nixexprs.tar.xz"
        install_url: "https://releases.nixos.org/nix/nix-2.24.15/install"
        extra_nix_config: |2
          experimental-features = nix-command flakes

    - run: nix flake check

    - run: nix-shell -p '(import <nixpkgs> {}).nixos-rebuild' --run 'nixos-rebuild build --flake .#nixos-flake-test'
