name: "plutus"
on:
  pull_request:
  push:
jobs:
  tests:
    name: plutus build configuration check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
       # Flakes do not like shallow clones
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v22
      with:
        install_url: "https://releases.nixos.org/nix/nix-2.13.5/install"
        extra_nix_config: |2
          experimental-features = nix-command flakes

    - run: nix flake check

    - run: nix build .#nixosConfigurations.plutus.config.system.build.toplevel -L
